//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicetypeHasOperatingsystem
    {
        public long DeviceType_fk { get; set; }
        public long Operatingsystem_fk { get; set; }
        public long Id { get; set; }
    
        public virtual Devicetype Devicetype { get; set; }
        public virtual Operatingsystem Operatingsystem { get; set; }
    }
}
