//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deviceport
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public long Device_fk { get; set; }
        public long Transportmedium_fk { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Transportmedium Transportmedium { get; set; }
    }
}
