//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interface
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Interface()
        {
            this.Accountings = new HashSet<Accounting>();
        }
    
        public long Id { get; set; }
        public int Network_fk { get; set; }
        public long Device_fk { get; set; }
        public string Ip_adress_v4 { get; set; }
        public string Mac_adresse { get; set; }
        public byte[] IsFullDuplex { get; set; }
        public Nullable<int> Bandwith { get; set; }
        public Nullable<short> Is_in_use { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounting> Accountings { get; set; }
        public virtual Device Device { get; set; }
        public virtual Network Network { get; set; }
    }
}
