//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pointofdelivery
    {
        public long Id { get; set; }
        public long Customer_id_fk { get; set; }
        public long Contact_id_fk { get; set; }
        public long Cocation_fk { get; set; }
        public string Designation { get; set; }
        public System.TimeSpan Timezone { get; set; }
        public short TimeZonePositiv { get; set; }
        public string NtpServerIp { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Location Location { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
