//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareService
    {
        public int Id { get; set; }
        public int HoursWorked { get; set; }
        public long Accounting_fk { get; set; }
    
        public virtual Accounting Accounting { get; set; }
    }
}
